// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iojxiiwbwcliipeuegjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvanhpaXdid2NsaWlwZXVlZ2puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODgxNzYsImV4cCI6MjA1OTk2NDE3Nn0.tniXrd4kjsplPEEv_Ee9QGmJBA4417HVtif1i2IOk3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);